### ISSUE TITLE
Error when points are too close to each other along an edge

### ISSUE THREAD

**Issue by prabhat-hegde** [nathanrooy/taxicab#5]
If points are too close to each other along the same edge, taxicab is currently unable to distinguish between the two points. For example,  if I try running the snippet of code below:

```python
import osmnx as ox
import matplotlib.pyplot as plt
import taxicab as tc
place_name = "Hanover, New Hampshire, United States"
graph = ox.graph_from_place(place_name, network_type='drive', simplify = "False")
source_address = "489 Hanover center Road, Hanover, NH"
destination_address = "471 Hanover center Road, Hanover, NH"
source = ox.geocode(source_address)
destination = ox.geocode(destination_address)
route = tc.distance.shortest_path(graph, source, destination)

```

I end up with the same edge for the route, resulting in the following error:

``` python
~/anaconda3/lib/python3.7/site-packages/taxicab/distance.py in shortest_path(G, orig, dest, use_shapely)
    448         # print(dest_edge[0])
    449         # annoying edge case: route matches first edge
--> 450         if route[0] == orig_edge[0] and route[1] == dest_edge[0]:
    451             route, orig_edge_p, dest_edge_p = route_across_multiple_edges(
    452                 G, orig_edge, dest_edge, orig, dest)

IndexError: list index out of range
```

`route` somehow ends up being a list with one element.

**Comment by nathanrooy** [comment]
Hi @1993Hegde, yes this is a know edge case. This will likely be resolved when I get around to implementing: issue https://github.com/nathanrooy/taxicab/issues/1

**Comment by nathanrooy** [comment]
@1993Hegde, I just pushed an update ([v0.0.2](https://github.com/nathanrooy/taxicab/releases/tag/v0.0.2)) which seems to resolve the issue you were having. Let me know if it works as expected!
